# Audio
PRODUCT_PROPERTY_OVERRIDES += \
    ro.build.scafe.version=2020A \
    ro.cfg.kill_heaviest_task=true \
    ro.config.media_sound=Media_preview_Touch_the_light.ogg \
    security.securehw.available=false \
    security.securenvm.available=false \
# Bluetooth
PRODUCT_PROPERTY_OVERRIDES += \
    net.bt.name=Android \
# Camera
PRODUCT_PROPERTY_OVERRIDES += \
    /dev/umts_ipc0 \
    rild.libargs=-d /dev/umts_ipc0 \
# Dalvik
PRODUCT_PROPERTY_OVERRIDES += \
    dalvik.vm.appimageformat=lz4 \
    dalvik.vm.dex2oat-Xms=64m \
    dalvik.vm.dex2oat-Xmx=512m \
    dalvik.vm.dex2oat-max-image-block-size=524288 \
    dalvik.vm.dex2oat-minidebuginfo=true \
    dalvik.vm.dex2oat-resolve-startup-strings=true \
    dalvik.vm.dexopt.secondary=true \
    dalvik.vm.heapgrowthlimit=192m \
    dalvik.vm.heapmaxfree=8m \
    dalvik.vm.heapminfree=512k \
    dalvik.vm.heapsize=512m \
    dalvik.vm.heapstartsize=8m \
    dalvik.vm.heaptargetutilization=0.75 \
    dalvik.vm.image-dex2oat-Xms=64m \
    dalvik.vm.image-dex2oat-Xmx=64m \
    dalvik.vm.lockprof.threshold=500 \
    dalvik.vm.minidebuginfo=true \
    dalvik.vm.usejit=true \
    dalvik.vm.usejitprofiles=true \
    ro.dalvik.vm.native.bridge=0 \
# FRP
PRODUCT_PROPERTY_OVERRIDES += \
    ro.frp.pst=/dev/block/persistent \
# Graphics
PRODUCT_PROPERTY_OVERRIDES += \
    debug.sf.disable_backpressure=1 \
    persist.demo.hdmirotationlock=false \
    ro.opengles.version=196610 \
    ro.sf.lcd_density=320 \
# Location
PRODUCT_PROPERTY_OVERRIDES += \
    ro.allow.mock.location=0 \
# Media
PRODUCT_PROPERTY_OVERRIDES += \
    exynos.ril.modempath=/dev/block/mmcblk0p5 \
# Misc
PRODUCT_PROPERTY_OVERRIDES += \
    debug.atrace.tags.enableflags=0 \
    debug.hwc.nodirtyregion=1 \
    debug.hwc.otf=1 \
    debug.hwc.winupdate=1 \
    import \
    /efs/factory.prop \
    keyguard.no_require_sim=true \
    net.dns1=8.8.8.8 \
    net.dns2=8.8.4.4 \
    persist.security.ams.enforcing=1 \
    pm.dexopt.ab-ota=speed-profile \
    pm.dexopt.bg-dexopt=speed-profile \
    pm.dexopt.boot=verify \
    pm.dexopt.first-boot=quicken \
    pm.dexopt.inactive=verify \
    pm.dexopt.install=speed-profile \
    pm.dexopt.shared=speed \
    restore.feature.use_samsung_smart_switch_flow=1 \
    ro.actionable_compatible_property.enabled=false \
    ro.adb.secure=1 \
    ro.apex.updatable=false \
    ro.arch=exynos7870 \
    ro.board.platform=universal7870 \
    ro.bootimage.build.date.utc=1641986849 \
    ro.bootimage.build.date=Wed \
    Jan \
    20:27:29 \
    KST \
    2022 \
    ro.bootimage.build.fingerprint=samsung/m10ltedx/m10lte:10/QP1A.190711.020/M105GDXS8CVA1:user/release-keys \
    ro.build.characteristics=phone \
    ro.build.selinux=1 \
    ro.build.version.sem=2901 \
    ro.build.version.sep=110000 \
    ro.cfg.custom_sw_limit=250 \
    ro.cfg.custom_tm_limit=1000 \
    ro.cfg.dha_2ndprop_thMB=2048 \
    ro.cfg.dha_cached_max=10 \
    ro.cfg.dha_cached_min=4 \
    ro.cfg.dha_empty_max=20 \
    ro.cfg.dha_lmk_scale=1 \
    ro.cfg.enable_userspace_lmk=true \
    ro.cfg.freelimit_val=13 \
    ro.cfg.upgrade_pressure=60 \
    ro.config.add_bonusEFK=2 \
    ro.config.custom_sw_limit=200 \
    ro.config.dha_cached_max=6 \
    ro.config.dha_cached_min=2 \
    ro.config.dha_dialer_except_th=1024 \
    ro.config.dha_empty_init=10 \
    ro.config.dha_empty_max=10 \
    ro.config.dha_empty_min=4 \
    ro.config.dha_lmk_scale=0.545 \
    ro.config.dmverity=G \
    ro.config.fha_enable=true \
    ro.config.freelimit_val=11 \
    ro.config.knox=v00 \
    ro.config.notification_sound_2=S_Charming_Bell.ogg \
    ro.config.ringtone_2=Basic_Bell.ogg \
    ro.config.upgrade_pressure=40 \
    ro.config.v_bonusEFK=30720 \
    ro.control_privapp_permissions=enforce \
    ro.debug_level=0x4948 \
    ro.debug_level=0x494d \
    ro.debuggable=0 \
    ro.error.receiver.default=com.samsung.receiver.error \
    ro.hardware.keystore=mdfpp \
    ro.hdcp2.rx=tz \
    ro.iorapd.enable=false \
    ro.kernel.qemu.gles=1 \
    ro.kernel.qemu=0 \
    ro.odm.build.date.utc=1641986849 \
    ro.odm.build.date=Wed \
    ro.odm.build.fingerprint=samsung/m10ltedx/m10lte:10/QP1A.190711.020/M105GDXS8CVA1:user/release-keys \
    ro.odm.build.id=QP1A.190711.020 \
    ro.odm.build.tags=release-keys \
    ro.odm.build.type=user \
    ro.odm.build.version.incremental=M105GDXS8CVA1 \
    ro.odm.build.version.release=10 \
    ro.odm.build.version.sdk=29 \
    ro.odm.product.cpu.abilist32=armeabi-v7a,armeabi \
    ro.odm.product.cpu.abilist64= \
    ro.odm.product.cpu.abilist=armeabi-v7a,armeabi \
    ro.oem_unlock_supported=1 \
    ro.opa.eligible_device=true \
    ro.postinstall.fstab.prefix=/system \
    ro.product.board=exynos7870 \
    ro.product.odm.brand=samsung \
    ro.product.odm.device=m10lte \
    ro.product.odm.manufacturer=samsung \
    ro.product.odm.model=SM-M105G \
    ro.product.odm.name=m10ltedx \
    ro.product.vendor.brand=samsung \
    ro.product.vendor.device=m10lte \
    ro.product.vendor.manufacturer=samsung \
    ro.product.vendor.model=SM-M105G \
    ro.product.vendor.name=m10ltedx \
    ro.secure=1 \
    ro.security.keystore.keytype=gak \
    ro.security.vpnpp.release=3.0 \
    ro.security.vpnpp.ver=2.1 \
    ro.system.build.version.sehi=2901 \
    ro.treble.enabled=true \
    ro.vendor.build.date.utc=1641986849 \
    ro.vendor.build.date=Wed \
    ro.vendor.build.id=QP1A.190711.020 \
    ro.vendor.build.security_patch= \
    ro.vendor.build.tags=release-keys \
    ro.vendor.build.type=user \
    ro.vendor.build.version.incremental=M105GDXS8CVA1 \
    ro.vendor.build.version.release=10 \
    ro.vendor.build.version.sdk=29 \
    ro.vendor.build.version.sehi=2901 \
    ro.vendor.cscsupported=1 \
    ro.vendor.product.cpu.abilist32=armeabi-v7a,armeabi \
    ro.vendor.product.cpu.abilist64= \
    ro.vendor.product.cpu.abilist=armeabi-v7a,armeabi \
    security.ADP.policy_version=00000000 \
    security.ADP.version=0 \
    security.ASKS.policy_version=00000000 \
    security.ASKS.rufs_enable=true \
    security.ASKS.time_value=00000000 \
    security.ASKS.version=0 \
    sys.config.activelaunch_enable=true \
# Perf
PRODUCT_PROPERTY_OVERRIDES += \
    security.perf_harden=1 \
# Radio
PRODUCT_PROPERTY_OVERRIDES += \
    exynos.ril.nvpath=/efs/ \
    persist.radio.sib16_support=1 \
    rild.libargs=-d \
    rild.libpath=/system/lib/libsec-ril.so \
    rild.libpath=/system/lib64/libsec-ril.so \
    ro.carrier=unknown \
    ro.telephony.default_cdma_sub=0 \
    ro.telephony.iwlan_operation_mode=legacy \
    ro.vendor.sec.radio.def_network=9 \
    vendor.sec.rild.libpath2=/vendor/lib/libsec-ril-dsds.so \
    vendor.sec.rild.libpath=/vendor/lib/libsec-ril.so \
# USB
PRODUCT_PROPERTY_OVERRIDES += \
    dev.usbsetting.embedded=On \
    dev.usbsetting.embedded=on \
    persist.sys.usb.config=none \
# WFD
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.wfdsupport=1 \
# WLAN
PRODUCT_PROPERTY_OVERRIDES += \
